# Site settings
title: Human Interaction and RObotics [HIRO] Group
email: alessandro.roncone@colorado.edu
url: https://hiro-group.ronc.one
phone: +1 (303) 735-6233
google-analytics-id:  G-76827T07Y0
description: "We Build the Future of Robotics and AI by looking at <ins>Humans as Models of Intelligence</ins>."
owner: Human Interaction and Robotics Group
owner-short: HIRO-group
owner-url: https://alessandro.ronc.one

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github-alt
    url: https://github.com/HIRO-group

meetings:
  semester: Fall 2025
  location: ECES 116
  note: " on Fridays at 11 am (biweekly)"

logo: /img/logo-square.svg
logopng: /img/logo-square.png
logo2: /img/logo-rect.svg
logo3: /img/logo-long-white-text.svg

# Postal address (add as many lines as necessary)
address:
  - line: 1111 Engineering Dr, ECST 322
  - line: Computer Science Department,
  - line: University of Colorado,
  - line: Boulder, 80309, CO, U.S.A.

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  highlighter: rouge
  toc_levels: "1,2,3"
permalink: pretty
plugins:
  - jekyll-sitemap
  - rouge
  - jekyll-seo-tag
  - jemoji
  #- jekyll-mentions

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
    values:
      type: "article"
  -
    scope:
      path: "_posts/wiki"
    values:
      category: "wiki"
  -
    scope:
      path: "_posts/news"
    values:
      category: "news"
  -
    scope:
      path: "_posts/research"
    values:
      category: "research"

  -
    scope:
      path: "_posts/research/subteams"
    values:
      type: "subteams"
      category: [research, subteams]

# Default colors (hex-codes without the leading hash-tag):
color:
  backdrop: "000000"                # This is the background, black
  embodied: "32FFB8"                # This is an electric green color (old green was 66a329)
  social: "F32B92"                  # This is an electric pink color (for red, use bf4040)
  accent: "00a0a0"                  # This is the old hiro blue accent color
  articletext: "ffffff"             # This is the text color, white
  secondarytext: "aeaeae"           # This is the secondary text color, light gray (to give some depth)
