# Site settings
title: Autonomous Robotics and Perception Group
email: Christoffer.Heckman@colorado.edu
url: https://arpg.colorado.edu
phone: +1-303-492-2961
google-analytics-id: 
description: "The ARPG Group, led by Christoffer Heckman at CU Boulder, conducts research in robotics, control theory, and perception."
owner: Autonomous Robotics and Perception Group
owner-short: ARPG
owner-url: http://www.ristoffer.ch/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github-alt
    url: https://github.com/ARPG
  - title: slack
    url: https://arpg.slack.com

meetings:
  semester: Fall 2019
  location: ECES 116 on Wednesdays from 1:30pm to 3pm [last meeting will be on December 16th]

logo: /img/logos/arpg-logo.png
logothumb: /img/logos/cu-logo.png

# Postal address (add as many lines as necessary)
address:
  - line: 1111 Engineering Dr, ECES 116
  - line: Computer Science Department,
  - line: University of Colorado,
  - line: Boulder, 80309, CO, U.S.A.

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  highlighter: rouge
  toc_levels: "1,2,3"
permalink: pretty
plugins:
  - jekyll-sitemap
  - rouge
  - jekyll-seo-tag
  - jemoji
  #- jekyll-mentions

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
    values:
      type: "article"
  -
    scope:
      path: "_posts/wiki"
    values:
      category: "wiki"
  -
    scope:
      path: "_posts/news"
    values:
      category: "research"
      subcategory: "news"

  -
    scope:
      path: "_posts/research"
    values:
      category: "research"
      subcategory: "research"

# Default colors (hex-codes without the leading hash-tag):
color:
  banner: 66a329                            # This is a green banner color (for red, use bf4040)
  articletext: 3c3c3c                       # This is the text color
  primary:  ffffff                          # This is the background of the logo, light gray
  secondary: 282828                         # This is dark gray
  secondary-alpha: rgba(40,40,40,.7)        # This is the same as the secondary color but with an alpha value
  # accent: 4982a7
  accent: 00a0a0                            # This is an electric blue accent
